### ISSUE TITLE
No Version working, Win 7 & Win 10

### ISSUE THREAD

**Issue by chogger** [matthewn4444/Lightpack-Filter-and-API#4] opened 2016-07-12 09:49 UTC
I am giving up with your Filter... I can't get it working. Am I missing any dependencies?

I installed a blank Win 10 x64 yesterday (after it didn't work in W7 x64), then installed all driver and MPC-HC (both Versions).

I used your setup.exe to install Lightpack Filter (first 0.6.2, then 0.6.3). And I can try whatever I want, your application never starts. No window, nothing happens. I see the nw.exe running but that is all.

So I think this is a hardware/driver problem? I use a Intel Pention G3220 processor (cpu & gpu)
Any ideas what might fix the problem?

**Comment by matthewn4444** [comment] 2016-07-12 09:52
I know what the issues are but I haven't had time to fix it. For some reason Node webkit is failing on some machines and the older binaries work with some versions of Windows. I will fix it in time but for now I do not have time.

**Comment by matthewn4444** [comment] 2017-01-12 09:21
If you are willing to help out, I can send you a version now to see if it runs on your system. I just updated the code to work on a PC I have that was able to reproduce the failure.

**Comment by chogger** [comment] 2017-01-12 09:22
Sure..! Will test it as soon as possible ;)

2017-01-12 10:21 GMT+01:00 Matthew Ng <notifications@github.com>:

**Comment by matthewn4444** [comment] 2017-01-12 09:35
Check releases for 0.6.4a and setup using the zip file. You can let me know if you are able to open the filter configurations or not.

**Comment by ranarn** [comment] 2017-01-12 16:45
I can confirm now that it works as intended on Windows 10.
Great job!

**Comment by flagg19** [comment] 2017-01-12 18:37
(Working for me too)

**Comment by matthewn4444** [comment] 2017-01-12 18:38
Great, I'm going to close this. Will hopefully have a full version up soon with the other fixes.

**Closed as completed by matthewn4444** 2017-01-12 18:38 UTC
